import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'local_llm_service.dart';
import 'cloud_llm_service.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../data/models/user_profile.dart';
import '../data/models/lesson.dart';
import 'dart:math';

class SmartPromptGenerator {
  final LocalLlmService _llm = LocalLlmService();
  final CloudLlmService _cloud = CloudLlmService();

  /// Dynamically synthezises a personalized lesson tailored 
  /// specifically to the student's identified performance regressions.
  Future<Lesson> generatePersonalizedLesson(UserProfile user) async {
    try {
      final cefr = user.baselineCompleted ? (user.baselineScores?.composite ?? 0.0) : 40.0;
      final String cefrTag = _getCefrFromScore(cefr);
      
      // Gather personalization context
      final String weakPoints = user.weakAreas.isNotEmpty 
          ? user.weakAreas.join(', ') 
          : 'General speaking accuracy';

      final String sysPrompt = '''
Task: Generate a highly personalized English Speaking Practice Session.
Student Profile:
- Level: $cefrTag
- Needs Improvement In: $weakPoints

Output STRICT raw JSON only, no markdown, no code blocks:
{
  "topic": "Short Topic Name",
  "description": "Encouraging description of why this helps",
  "emoji": "🎨",
  "prompts": ["Question 1", "Question 2", "Question 3"]
}
Rules:
- All vocabulary must strictly be suitable for a $cefrTag learner.
- Address weak points ($weakPoints) indirectly via the subject matter.
- Ensure questions are open-ended and engaging.
''';

      debugPrint('SmartPrompt: Generating dynamic content for level $cefrTag…');
      
      final prefs = await SharedPreferences.getInstance();
      final useOfflineOnly = prefs.getBool('use_offline_only') ?? false;
      String raw = '';

      if (!useOfflineOnly && await _cloud.isOnline()) {
        debugPrint('SmartPrompt: Dispatching request to Gemini Cloud…');
        raw = await _cloud.generateText(sysPrompt);
      } else {
        debugPrint('SmartPrompt: Loading local LLM for inference…');
        await _llm.loadModel(); 
        raw = await _llm.smartGenerate(sysPrompt);
        await _llm.unloadModel();
      }

      // Parse logic
      final cleaned = raw.replaceAll(RegExp(r'```(json)?'), '').trim();
      final Map<String, dynamic> data = jsonDecode(cleaned);

      return Lesson(
        id: 'dynamic_${DateTime.now().millisecondsSinceEpoch}',
        cefrLevel: cefrTag,
        topic: data['topic'] ?? 'Personalized Drill',
        description: data['description'] ?? 'Dynamic drill generated by your tutor.',
        emoji: data['emoji'] ?? '💡',
        prompts: List<String>.from(data['prompts'] ?? ['Tell me about your day']),
      );

    } catch (e) {
      debugPrint('SmartPrompt Gen Error: $e. Falling back to standard curriculum.');
      // Seamless fallback to static curriculum if LLM generation fails offline or times out
      final fallbackGroup = LessonLibrary.lessons.where((l) => user.baselineCompleted ? l.cefrLevel == _getCefrFromScore(user.baselineScores?.composite ?? 0) : l.cefrLevel == 'A1').toList();
      return fallbackGroup.isNotEmpty ? fallbackGroup[Random().nextInt(fallbackGroup.length)] : LessonLibrary.lessons.first;
    }
  }

  String _getCefrFromScore(double score) {
    if (score >= 85) return 'C2';
    if (score >= 75) return 'C1';
    if (score >= 65) return 'B2';
    if (score >= 50) return 'B1';
    if (score >= 40) return 'A2';
    return 'A1';
  }
}
